apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: karpenter-provisioner
spec:    
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["t3.medium", "t3.large", "t3.xlarge"]  
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["ap-northeast-2a", "ap-northeast-2c"]      
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]  
  limits:
    resources:
      cpu: "1000"
      memory: 1000Gi
  ttlSecondsAfterEmpty: 30 # Daemonset 즉, Deployment, svc등 한개도 없을 때 삭제한다는 옵션
  labels:
    role: ops
    provision: karpenter
  provider:
    securityGroupSelector:
      karpenter.sh/discovery: unite-eks-cluster
    subnetSelector:
      karpenter.sh/discovery: unite-eks-cluster
    # tags:
    #   Name: karpenter.sh/provisioner-name/karpenter-provisioner
    #   karpenter.sh/discovery: unite-eks-cluster
