extraEnv:
  - name: AWS_REGION
    value: "us-east-1"
config:
  argocd:
    serverAddress: "argocd-server"
  registries:
    - name: ECR
      api_url: https://123456789.dkr.ecr.eu-west-1.amazonaws.com
      prefix: 123456789.dkr.ecr.eu-west-1.amazonaws.com
      ping: yes
      insecure: no
      credentials: ext:/scripts/ecr.sh
      credsexpire: 10h
authScripts:
  enabled: true
  scripts:
    ecr.sh: |
      #!/bin/sh
      aws ecr --region $AWS_REGION get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d
serviceAccount:
  create: false
  name: "argocd-image-updater"
nodeSelector:
  management: addon
tolerations:
  - key: management
    value: addon
    effect: NoSchedule
