apiVersion: v1
kind: Secret
metadata:
  name: pods-secret
  namespace: hrdkorea
stringData:
  MYSQL_USER: admin
  MYSQL_PASSWORD: supersecretpassword

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: skills-deployment
  namespace: hrdkorea
  labels:
    skills/dedicated: skills
spec:
  replicas: 2
  selector:
    matchLabels:
      skills/dedicated: skills
  template:
    metadata:
      labels:
        skills/dedicated: skills
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: skills/dedicated
                operator: In
                values:
                - skills
      containers:
        - name: skills-container
          image: dkr.ecr.amazonaws.com/hrdkorea:lastest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: MYSQL_PORT
            - name: MYSQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-secret
                  key: MYSQL_DBNAME
            - name: AWS_REGION
      restartPolicy: Always
