apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-grace
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2 # default 0, 어플리케이션이 시작될때까지 기다리는 시간입니다.
          periodSeconds: 5 # default 10, Healthcheck 요청을 보내는 주기(Interval)입니다.
          timeoutSeconds: 3 # default 1, Healthcheck 요청의 타임아웃 값입니다.
          failureThreshold: 3 # default 3, 3번 이상 실패하면 파드를 재시작합니다.
          successThreshold: 1 # default 1, 1번 이상 성공하면 Running 상태로 넘어갑니다.      
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
      terminationGracePeriodSeconds: 60
      # SIGKILL 신호를 받기까지 60초의 유예시간이 주어집니다.
      # 기본값은 30초입니다.
      # 해당 manifest파일은 해당 컨테이너가 stop되면 /usr/sbin/nginx -s quit 명령어를 통해 nginx를 종료한다. 그러면 gracefulshutdown이 동작되어
      # 60초 뒤에 해당 컨테이너가 종료된다.

      # kubectl rollout pause deploy nginx-grace