apiVersion: v1
kind: Service
metadata:
  name: static-svc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: static
    version: '0.1'
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
