apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: yelb
  name: app-server
spec:
  awsName: app-server-virtual-router
  listeners:
  - portMapping:
      port: 4567
      protocol: http
  routes:
  - name: route-to-yelb-appserver
    httpRoute:
      match:
        prefix: /
      action:
        weightedTargets:
        - virtualNodeRef:
            name: app-server
          weight: 1
      retryPolicy:
        maxRetries: 2
        preRetryTimeout:
          unit: ms
          value: 2000
        httpRetryEvents:
          - server-error
          - client-error
          - gateway-error