apiVersion: apps/v1
kind: Deployment
metadata:
  name : test-deployment
spec:
  strategy: # 요기
    type: RollingUpdate
    rollingUpdate:
      maxUnvailable: 3
      maxSurge: 4
  replicas: 4
  selector:
    matchLabels:
      app: test-pod
  template:
    metadata:
      labels:
        app: test-pod
    spec:
      containers:
        - name: test-pod
          image: ghcr.io/dispiny/echo_server:1.0 # 단순히 요청을 받으면 version을 > 리턴해주는 서버이다
          ports:
            - containerPort: 80